[build]
  command = "npm install -g @angular/cli && ng build --prod --output-path docs --base-href personal-website"
  publish = "docs/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
